require "user.options"
require "user.keymaps"

-- require "user.plugins2"
-- require "user.coc"
-- require "user.autopairs"
-- require "user.comment"
-- require "user.telescope"
-- require "user.alpha"
-- require "user.project"
-- require "user.whichkey"
-- require "user.lualine"
-- require "user.toggleterm"

require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
-- require "user.dap"
require "user.telescope"
require "user.gitsigns"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
require "user.toggleterm"
require "user.project"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
